# Generated by Django 5.2.8 on 2025-11-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipo_url', models.URLField(verbose_name='IPO Page URL')),
                ('rne_url', models.URLField(verbose_name='Refer & Earn Page URL')),
            ],
        ),
    ]
